/**
 * Development Seed Data
 *
 * Creates sample data for local development and testing
 */

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Seeding development data...");

  // Create test client
  const client = await prisma.client.upsert({
    where: { slug: "demo-client" },
    update: {},
    create: {
      name: "Demo Client",
      slug: "demo-client",
      tier: "PRO",
      status: "ACTIVE",
      maxUsers: 10,
      maxWorkflows: 20,
      maxAdAccounts: 5,
      settings: {
        timezone: "America/Mexico_City",
        reportSchedule: "weekly",
      },
    },
  });

  console.log("✅ Created client:", client.name);

  // Create test user
  const user = await prisma.user.upsert({
    where: { email: "admin@demo.com" },
    update: {},
    create: {
      authorizerId: "auth-user-demo-001", // Dummy ID for development
      email: "admin@demo.com",
      // passwordHash: DEPRECATED - handled by Authorizer
      firstName: "Admin",
      lastName: "User",
      role: "ADMIN",
      status: "ACTIVE",
      // emailVerified: DEPRECATED - handled by Authorizer
      clientId: client.id,
    },
  });

  console.log("✅ Created user:", user.email);

  // Create test ad account
  const adAccount = await prisma.adAccount.upsert({
    where: { metaAdAccountId: "act_123456789" },
    update: {},
    create: {
      metaAdAccountId: "act_123456789",
      name: "Demo Ad Account",
      accessToken: "DUMMY_ACCESS_TOKEN_FOR_DEV",
      currency: "USD",
      status: "ACTIVE",
      clientId: client.id,
    },
  });

  console.log("✅ Created ad account:", adAccount.name);

  // Create test workflow
  const workflow = await prisma.workflow.upsert({
    where: { n8nWorkflowId: "workflow-001" },
    update: {},
    create: {
      name: "Weekly Storytelling Report",
      description: "Automated weekly report with storytelling narrative",
      type: "WEEKLY_REPORT",
      status: "ACTIVE",
      n8nWorkflowId: "workflow-001",
      schedule: "0 8 * * 1", // Every Monday at 8 AM
      clientId: client.id,
      adAccountId: adAccount.id,
      createdBy: user.id,
    },
  });

  console.log("✅ Created workflow:", workflow.name);

  // Create sample execution log
  const execution = await prisma.executionLog.create({
    data: {
      status: "SUCCESS",
      startedAt: new Date(),
      completedAt: new Date(),
      duration: 15432, // 15.4 seconds
      apiCallsUsed: 8,
      clientId: client.id,
      workflowId: workflow.id,
      adAccountId: adAccount.id,
      executedBy: user.id,
      output: {
        campaignsProcessed: 5,
        metricsCalculated: 50,
        reportGenerated: true,
      },
    },
  });

  console.log("✅ Created execution log");

  // Create sample report
  const report = await prisma.report.create({
    data: {
      title: "Weekly Performance Report - Week 47",
      type: "WEEKLY_STORYTELLING",
      status: "SENT",
      periodStart: new Date("2025-11-18"),
      periodEnd: new Date("2025-11-24"),
      content:
        "## Sample Report\n\nThis is a sample report generated by the system.",
      recipients: ["client@example.com"],
      sentAt: new Date(),
      clientId: client.id,
      userId: user.id,
      workflowId: workflow.id,
      adAccountId: adAccount.id,
      executionLogId: execution.id,
    },
  });

  console.log("✅ Created report:", report.title);

  console.log("\n🎉 Seed completed successfully!");
  console.log("\nTest credentials:");
  console.log("  Email: admin@demo.com");
  console.log("  Client: demo-client");
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
